version: "3"
services:
  nginx:
    image: nginx:1.15
    ports:
      - 80:80
    volumes:
      - ./source:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./source:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel_sample_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel_sample_user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
